/**
 * Entity Registry
 * Defines all NPC and monster types with their properties,
 * movement flags, and sprite information.
 * 
 * All frame names verified against actual atlas JSON files.
 * characters.json frames: hero_idle, hero_walk_1/2/3, hero_side_1, hero_walk_back_1/2,
 *   hero_lantern, hero_lantern_idle, hero_lantern_walk_1/2/3,
 *   guard_idle, guard_walk_1/2/3, guard_side_1/2, guard_back_1/2,
 *   apprentice_idle, apprentice_walk_1/2, apprentice_side_1, apprentice_back_1,
 *   scholar_idle, scholar_walk_1/2, scholar_side_1,
 *   merchant_idle, merchant_walk_1/2, merchant_side_1,
 *   elder_idle, elder_walk_1/2, elder_side_1,
 *   child_idle, child_walk_1/2, child_side_1
 */

import { EntityMovementFlags, DEFAULT_FLAGS, SHADOW_FLAGS, GHOST_FLAGS } from './TileSystem';

export type EntityState = 'idle' | 'walk' | 'run' | 'attack' | 'dead' | 'fainted' | 'frozen' | 'alert';

export interface EntityDefinition {
  id: string;
  name: string;
  type: 'npc' | 'monster' | 'boss';
  atlas: string;
  frames: Record<EntityState, string | string[]>;  // frame name(s) per state
  movementFlags: EntityMovementFlags;
  hp: number;
  speed: number;
  damage?: number;           // Damage dealt to player on contact
  dialogueKey?: string;      // Key in StorySystem dialogues
  canWander?: boolean;       // Does this NPC wander around?
  wanderRadius?: number;     // How far from home position to wander (tiles)
  isHostile?: boolean;       // Attacks player on sight
  sightRange?: number;       // How many tiles away to detect player
  fleeFromLight?: boolean;   // Shadow monsters flee from light
  displaySize?: number;      // Override display size (default 48)
  tileWidth?: number;        // How many tiles wide (default 1)
  tileHeight?: number;       // How many tiles tall (default 1)
  mathDifficulty?: number;   // If set, triggers math challenge (1-5)
  fleeRange?: number;         // Distance in pixels at which peaceful animals flee from player
}

// ===================== VISUAL TINTS =====================
// Tint colors for different monster types (applied to sprites)
export const MONSTER_TINTS: Record<string, number> = {
  shadow_small: 0x000000,
  shadow_stalker: 0x000033,
  shadow_boss: 0x110011,
  goblin: 0x44aa44,
  skeleton: 0xddddcc,
  ghost: 0xaaddff,
  slime: 0x44ff88,
};

// Alpha values for different monster types
export const MONSTER_ALPHA: Record<string, number> = {
  shadow_small: 0.75,
  shadow_stalker: 0.80,
  shadow_boss: 0.90,
  goblin: 1.0,
  skeleton: 1.0,
  ghost: 0.65,
  slime: 0.85,
};

// ===================== NPC DEFINITIONS =====================

export const NPC_DEFINITIONS: Record<string, EntityDefinition> = {
  guard: {
    id: 'guard',
    name: 'Guard Aldric',
    type: 'npc',
    atlas: 'characters',
    frames: {
      idle: 'guard_idle',
      walk: ['guard_walk_1', 'guard_walk_2', 'guard_walk_3'],
      run: ['guard_walk_1', 'guard_walk_2', 'guard_walk_3'],
      attack: 'guard_idle',
      dead: 'guard_idle',       // Fallback - no dead frame yet
      fainted: 'guard_idle',    // Fallback
      frozen: 'guard_idle',     // Fallback
      alert: 'guard_side_1',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 100,
    speed: 80,
    dialogueKey: 'guard_choice',
    canWander: false,
  },

  guard2: {
    id: 'guard2',
    name: 'Guard Berin',
    type: 'npc',
    atlas: 'characters',
    frames: {
      idle: 'guard_idle',
      walk: ['guard_walk_1', 'guard_walk_2', 'guard_walk_3'],
      run: ['guard_walk_1', 'guard_walk_2', 'guard_walk_3'],
      attack: 'guard_idle',
      dead: 'guard_idle',
      fainted: 'guard_idle',
      frozen: 'guard_idle',
      alert: 'guard_side_2',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 100,
    speed: 80,
    dialogueKey: 'guard_choice',
    canWander: true,
    wanderRadius: 2,
  },

  apprentice: {
    id: 'apprentice',
    name: 'Mira the Apprentice',
    type: 'npc',
    atlas: 'characters',
    frames: {
      idle: 'apprentice_idle',
      walk: ['apprentice_walk_1', 'apprentice_walk_2'],
      run: ['apprentice_walk_1', 'apprentice_walk_2'],
      attack: 'apprentice_idle',
      dead: 'apprentice_idle',
      fainted: 'apprentice_idle',
      frozen: 'apprentice_idle',
      alert: 'apprentice_side_1',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 60,
    speed: 100,
    dialogueKey: 'apprentice_quiz',
    canWander: true,
    wanderRadius: 3,
  },

  merchant: {
    id: 'merchant',
    name: 'Trader Brom',
    type: 'npc',
    atlas: 'characters',
    frames: {
      idle: 'merchant_idle',
      walk: ['merchant_walk_1', 'merchant_walk_2'],
      run: ['merchant_walk_1', 'merchant_walk_2'],
      attack: 'merchant_idle',
      dead: 'merchant_idle',
      fainted: 'merchant_idle',
      frozen: 'merchant_idle',
      alert: 'merchant_side_1',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 60,
    speed: 60,
    dialogueKey: 'merchant_fill',
    canWander: false,
  },

  elder: {
    id: 'elder',
    name: 'Elder Theron',
    type: 'npc',
    atlas: 'characters',
    frames: {
      idle: 'elder_idle',
      walk: ['elder_walk_1', 'elder_walk_2'],
      run: ['elder_walk_1', 'elder_walk_2'],
      attack: 'elder_idle',
      dead: 'elder_idle',
      fainted: 'elder_idle',
      frozen: 'elder_idle',
      alert: 'elder_side_1',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 40,
    speed: 50,
    dialogueKey: 'elder_riddle',
    canWander: false,
  },

  scholar: {
    id: 'scholar',
    name: 'Scholar Vera',
    type: 'npc',
    atlas: 'characters',
    frames: {
      idle: 'scholar_idle',
      walk: ['scholar_walk_1', 'scholar_walk_2'],
      run: ['scholar_walk_1', 'scholar_walk_2'],
      attack: 'scholar_idle',
      dead: 'scholar_idle',
      fainted: 'scholar_idle',
      frozen: 'scholar_idle',
      alert: 'scholar_side_1',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 50,
    speed: 60,
    dialogueKey: 'scholar_quiz',
    canWander: false,
    mathDifficulty: 1,
  },

  child: {
    id: 'child',
    name: 'Young Pip',
    type: 'npc',
    atlas: 'characters',
    frames: {
      idle: 'child_idle',
      walk: ['child_walk_1', 'child_walk_2'],
      run: ['child_walk_1', 'child_walk_2'],
      attack: 'child_idle',
      dead: 'child_idle',
      fainted: 'child_idle',
      frozen: 'child_idle',
      alert: 'child_side_1',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 30,
    speed: 120,
    dialogueKey: 'child_quiz',
    canWander: true,
    wanderRadius: 4,
  },

  blacksmith: {
    id: 'blacksmith',
    name: 'Blacksmith Gorrin',
    type: 'npc',
    atlas: 'characters',
    frames: {
      idle: 'guard_idle',       // Use guard as placeholder
      walk: ['guard_walk_1', 'guard_walk_2'],
      run: ['guard_walk_1', 'guard_walk_2'],
      attack: 'guard_idle',
      dead: 'guard_idle',
      fainted: 'guard_idle',
      frozen: 'guard_idle',
      alert: 'guard_side_1',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 80,
    speed: 60,
    dialogueKey: 'blacksmith_quiz',
    canWander: false,
  },

  innkeeper: {
    id: 'innkeeper',
    name: 'Innkeeper Marta',
    type: 'npc',
    atlas: 'characters',
    frames: {
      idle: 'merchant_idle',    // Use merchant as placeholder
      walk: ['merchant_walk_1', 'merchant_walk_2'],
      run: ['merchant_walk_1', 'merchant_walk_2'],
      attack: 'merchant_idle',
      dead: 'merchant_idle',
      fainted: 'merchant_idle',
      frozen: 'merchant_idle',
      alert: 'merchant_side_1',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 60,
    speed: 60,
    dialogueKey: 'innkeeper_riddle',
    canWander: false,
  },

  ranger: {
    id: 'ranger',
    name: 'Ranger Sylva',
    type: 'npc',
    atlas: 'characters',
    frames: {
      idle: 'apprentice_idle',
      walk: ['apprentice_walk_1', 'apprentice_walk_2'],
      run: ['apprentice_walk_1', 'apprentice_walk_2'],
      attack: 'apprentice_side_1',
      dead: 'apprentice_idle',
      fainted: 'apprentice_idle',
      frozen: 'apprentice_idle',
      alert: 'apprentice_side_1',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 80,
    speed: 100,
    dialogueKey: 'ranger',
    canWander: true,
    wanderRadius: 3,
  },

  hermit: {
    id: 'hermit',
    name: 'Old Hermit',
    type: 'npc',
    atlas: 'characters',
    frames: {
      idle: 'elder_idle',
      walk: ['elder_walk_1', 'elder_walk_2'],
      run: ['elder_walk_1', 'elder_walk_2'],
      attack: 'elder_idle',
      dead: 'elder_idle',
      fainted: 'elder_idle',
      frozen: 'elder_idle',
      alert: 'elder_side_1',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 30,
    speed: 40,
    dialogueKey: 'hermit',
    canWander: false,
  },

  // Sick villager — shows 🤒 bubble, no dialogue
  sick_villager: {
    id: 'sick_villager',
    name: 'Sick Villager',
    type: 'npc',
    atlas: 'characters',
    frames: {
      idle: 'child_idle',
      walk: ['child_walk_1', 'child_walk_2'],
      run: ['child_walk_1', 'child_walk_2'],
      attack: 'child_idle',
      dead: 'child_idle',
      fainted: 'child_idle',
      frozen: 'child_idle',
      alert: 'child_side_1',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 10,
    speed: 30,
    canWander: false,
    // No dialogueKey — shows 🤒 bubble automatically (id contains 'sick')
  },

  // Sleeping elder — shows 💤 bubble, no dialogue
  sleeping_elder: {
    id: 'sleeping_elder',
    name: 'Sleeping Elder',
    type: 'npc',
    atlas: 'characters',
    frames: {
      idle: 'elder_idle',
      walk: ['elder_walk_1', 'elder_walk_2'],
      run: ['elder_walk_1', 'elder_walk_2'],
      attack: 'elder_idle',
      dead: 'elder_idle',
      fainted: 'elder_idle',
      frozen: 'elder_idle',
      alert: 'elder_side_1',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 20,
    speed: 25,
    canWander: false,
    // No dialogueKey — shows 💤 bubble automatically (id contains 'sleep')
  },
};

// ===================== MONSTER DEFINITIONS =====================

export const MONSTER_DEFINITIONS: Record<string, EntityDefinition> = {
  shadow_small: {
    id: 'shadow_small',
    name: 'Shadow Wisp',
    type: 'monster',
    atlas: 'creatures',
    frames: {
      idle: 'shadow_wraith_idle_night_f01',
      walk: ['shadow_wraith_float_down_f01', 'shadow_wraith_float_down_f02'],
      run: ['shadow_wraith_float_down_f03', 'shadow_wraith_float_down_f04'],
      attack: 'shadow_wraith_shadow_strike_f01',
      dead: 'shadow_wraith_idle_day_f01',
      fainted: 'shadow_wraith_idle_day_f01',
      frozen: 'shadow_wraith_idle_day_f02',
      alert: 'shadow_wraith_shadow_strike_f02',
    },
    movementFlags: SHADOW_FLAGS,
    hp: 30,
    speed: 60,
    damage: 1,
    isHostile: false,
    sightRange: 5,
    fleeFromLight: true,
    displaySize: 32,            // Smaller than player (1 tile)
  },

  shadow_stalker: {
    id: 'shadow_stalker',
    name: 'Shadow Stalker',
    type: 'monster',
    atlas: 'creatures',
    frames: {
      idle: 'void_creature_idle_f01',
      walk: ['void_creature_move_down_f01', 'void_creature_move_down_f02', 'void_creature_move_down_f03'],
      run: ['void_creature_move_down_f02', 'void_creature_move_down_f03', 'void_creature_move_down_f04'],
      attack: 'void_creature_consume_f01',
      dead: 'void_creature_idle_f04',
      fainted: 'void_creature_idle_f04',
      frozen: 'void_creature_idle_f02',
      alert: 'void_creature_consume_f02',
    },
    movementFlags: SHADOW_FLAGS,
    hp: 60,
    speed: 90,
    damage: 2,
    isHostile: true,
    sightRange: 6,
    fleeFromLight: true,
    displaySize: 40,
  },

  shadow_boss: {
    id: 'shadow_boss',
    name: 'Shadow Lord',
    type: 'boss',
    atlas: 'creatures',
    frames: {
      idle: 'dark_knight_idle_f01',
      walk: ['dark_knight_walk_down_f01', 'dark_knight_walk_down_f02', 'dark_knight_walk_down_f03'],
      run: ['dark_knight_walk_down_f02', 'dark_knight_walk_down_f03', 'dark_knight_walk_down_f04'],
      attack: 'dark_knight_sword_slash_f01',
      dead: 'dark_knight_idle_f04',
      fainted: 'dark_knight_idle_f04',
      frozen: 'dark_knight_idle_f02',
      alert: 'dark_knight_night_power_f01',
    },
    movementFlags: SHADOW_FLAGS,
    hp: 200,
    speed: 70,
    damage: 5,
    isHostile: true,
    sightRange: 8,
    fleeFromLight: false,       // Boss doesn't flee!
    displaySize: 56,
  },

  goblin: {
    id: 'goblin',
    name: 'Forest Boar',
    type: 'monster',
    atlas: 'creatures',
    frames: {
      idle: 'boar_idle_f01',
      walk: ['boar_walk_down_f01', 'boar_walk_down_f02', 'boar_walk_down_f03'],
      run: ['boar_charge_f01', 'boar_charge_f02', 'boar_charge_f03'],
      attack: 'boar_gore_f01',
      dead: 'boar_idle_f04',
      fainted: 'boar_idle_f04',
      frozen: 'boar_idle_f02',
      alert: 'boar_charge_f01',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 40,
    speed: 80,
    damage: 1,
    isHostile: true,
    sightRange: 4,
    displaySize: 36,
  },

  wolf: {
    id: 'wolf',
    name: 'Forest Wolf',
    type: 'monster',
    atlas: 'creatures',
    frames: {
      idle: 'wolf_idle_f01',
      walk: ['wolf_walk_down_f01', 'wolf_walk_down_f02', 'wolf_walk_down_f03'],
      run: ['wolf_sprint_f01', 'wolf_sprint_f02', 'wolf_sprint_f03'],
      attack: 'wolf_bite_f01',
      dead: 'wolf_sleep_f01',
      fainted: 'wolf_sleep_f01',
      frozen: 'wolf_idle_f01',
      alert: 'wolf_howl_f01',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 50,
    speed: 110,
    damage: 2,
    isHostile: true,
    sightRange: 5,
    canWander: true,
    wanderRadius: 5,
    displaySize: 42,
  },

  zombie: {
    id: 'zombie',
    name: 'Graveyard Zombie',
    type: 'monster',
    atlas: 'creatures',
    frames: {
      idle: 'zombie_idle_night_f01',
      walk: ['zombie_walk_down_f01', 'zombie_walk_down_f02', 'zombie_walk_down_f03'],
      run: ['zombie_walk_down_f02', 'zombie_walk_down_f03'],
      attack: 'zombie_grab_f01',
      dead: 'zombie_fall_f01',
      fainted: 'zombie_fall_f01',
      frozen: 'zombie_idle_day_f01',
      alert: 'zombie_bite_f01',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 55,
    speed: 48,
    damage: 2,
    isHostile: true,
    sightRange: 4,
    canWander: true,
    wanderRadius: 3,
    displaySize: 42,
  },

  demon: {
    id: 'demon',
    name: 'Cinder Demon',
    type: 'monster',
    atlas: 'creatures',
    frames: {
      idle: 'demon_idle_f01',
      walk: ['demon_walk_down_f01', 'demon_walk_down_f02', 'demon_walk_down_f03'],
      run: ['demon_wing_dash_f01', 'demon_wing_dash_f02'],
      attack: 'demon_fire_claw_f01',
      dead: 'demon_idle_f01',
      fainted: 'demon_idle_f01',
      frozen: 'demon_idle_f02',
      alert: 'demon_hellfire_f01',
    },
    movementFlags: { ...DEFAULT_FLAGS, canFly: true },
    hp: 85,
    speed: 82,
    damage: 3,
    isHostile: true,
    sightRange: 6,
    canWander: true,
    wanderRadius: 4,
    displaySize: 50,
  },

  spider: {
    id: 'spider',
    name: 'Cave Spider',
    type: 'monster',
    atlas: 'creatures',
    frames: {
      idle: 'spider_idle_f01',
      walk: ['spider_walk_down_f01', 'spider_walk_down_f02', 'spider_walk_down_f03'],
      run: ['spider_walk_down_f02', 'spider_walk_down_f03', 'spider_walk_down_f04'],
      attack: 'spider_bite_f01',
      dead: 'spider_hang_f01',
      fainted: 'spider_hang_f01',
      frozen: 'spider_idle_f02',
      alert: 'spider_web_shoot_f01',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 35,
    speed: 92,
    damage: 2,
    isHostile: true,
    sightRange: 5,
    canWander: true,
    wanderRadius: 4,
    displaySize: 36,
  },

  giant_bug: {
    id: 'giant_bug',
    name: 'Giant Bug',
    type: 'monster',
    atlas: 'creatures',
    frames: {
      idle: 'giant_bug_idle_f01',
      walk: ['giant_bug_walk_down_f01', 'giant_bug_walk_down_f02', 'giant_bug_walk_down_f03'],
      run: ['giant_bug_charge_f01', 'giant_bug_charge_f02', 'giant_bug_charge_f03'],
      attack: 'giant_bug_bite_f01',
      dead: 'giant_bug_idle_f04',
      fainted: 'giant_bug_idle_f04',
      frozen: 'giant_bug_idle_f02',
      alert: 'giant_bug_burrow_f01',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 48,
    speed: 78,
    damage: 2,
    isHostile: true,
    sightRange: 4,
    canWander: true,
    wanderRadius: 4,
    displaySize: 38,
  },

  giant_snake: {
    id: 'giant_snake',
    name: 'Giant Snake',
    type: 'monster',
    atlas: 'creatures',
    frames: {
      idle: 'giant_snake_idle_f01',
      walk: ['giant_snake_slither_down_f01', 'giant_snake_slither_down_f02', 'giant_snake_slither_down_f03'],
      run: ['giant_snake_slither_down_f02', 'giant_snake_slither_down_f03', 'giant_snake_slither_down_f04'],
      attack: 'giant_snake_strike_f01',
      dead: 'giant_snake_idle_f04',
      fainted: 'giant_snake_idle_f04',
      frozen: 'giant_snake_idle_f02',
      alert: 'giant_snake_hiss_f01',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 58,
    speed: 82,
    damage: 3,
    isHostile: true,
    sightRange: 5,
    canWander: true,
    wanderRadius: 4,
    displaySize: 42,
  },

  troll: {
    id: 'troll',
    name: 'Troll',
    type: 'monster',
    atlas: 'creatures',
    frames: {
      idle: 'troll_idle_f01',
      walk: ['troll_walk_down_f01', 'troll_walk_down_f02', 'troll_walk_down_f03'],
      run: ['troll_walk_down_f02', 'troll_walk_down_f03', 'troll_walk_down_f04'],
      attack: 'troll_club_smash_f01',
      dead: 'troll_sleep_f01',
      fainted: 'troll_sleep_f01',
      frozen: 'troll_idle_f02',
      alert: 'troll_throw_rock_f01',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 95,
    speed: 48,
    damage: 4,
    isHostile: true,
    sightRange: 5,
    canWander: true,
    wanderRadius: 3,
    displaySize: 52,
  },

  golem: {
    id: 'golem',
    name: 'Stone Golem',
    type: 'boss',
    atlas: 'creatures',
    frames: {
      idle: 'golem_idle_f01',
      walk: ['golem_walk_down_f01', 'golem_walk_down_f02', 'golem_walk_down_f03'],
      run: ['golem_walk_down_f02', 'golem_walk_down_f03', 'golem_walk_down_f04'],
      attack: 'golem_punch_f01',
      dead: 'golem_dormant_f01',
      fainted: 'golem_dormant_f01',
      frozen: 'golem_idle_f02',
      alert: 'golem_stomp_f01',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 140,
    speed: 42,
    damage: 5,
    isHostile: true,
    sightRange: 6,
    canWander: true,
    wanderRadius: 3,
    displaySize: 58,
  },

  skeleton: {
    id: 'skeleton',
    name: 'Skeleton',
    type: 'monster',
    atlas: 'creatures',
    frames: {
      idle: 'skeleton_idle_f01',
      walk: ['skeleton_walk_down_f01', 'skeleton_walk_down_f02', 'skeleton_walk_down_f03'],
      run: ['skeleton_night_march_f01', 'skeleton_night_march_f02'],
      attack: 'skeleton_sword_attack_f01',
      dead: 'skeleton_reassemble_f01',
      fainted: 'skeleton_reassemble_f01',
      frozen: 'skeleton_idle_f02',
      alert: 'skeleton_sword_attack_f02',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 45,
    speed: 65,
    damage: 2,
    isHostile: true,
    sightRange: 5,
    displaySize: 44,
  },

  ghost: {
    id: 'ghost',
    name: 'Restless Ghost',
    type: 'monster',
    atlas: 'creatures',
    frames: {
      idle: 'ghost_idle_night_f01',
      walk: ['ghost_float_down_f01', 'ghost_float_down_f02', 'ghost_float_down_f03'],
      run: ['ghost_float_right_f01', 'ghost_float_right_f02'],
      attack: 'ghost_possess_f01',
      dead: 'ghost_idle_day_f01',
      fainted: 'ghost_idle_day_f01',
      frozen: 'ghost_idle_day_f02',
      alert: 'ghost_phase_wall_f01',
    },
    movementFlags: GHOST_FLAGS,
    hp: 35,
    speed: 70,
    damage: 1,
    isHostile: false,
    sightRange: 4,
    displaySize: 40,
  },

  slime: {
    id: 'slime',
    name: 'Slime',
    type: 'monster',
    atlas: 'creatures',
    frames: {
      idle: 'slime_idle_f01',
      walk: ['slime_move_left_f01', 'slime_move_right_f01'],
      run: ['slime_move_left_f01', 'slime_move_right_f01'],
      attack: 'slime_angry_f01',
      dead: 'slime_idle_f02',
      fainted: 'slime_idle_f02',
      frozen: 'slime_idle_f01',
      alert: 'slime_angry_f01',
    },
    movementFlags: { ...DEFAULT_FLAGS, canSwim: true },
    hp: 25,
    speed: 40,
    damage: 1,
    isHostile: false,
    sightRange: 3,
    displaySize: 32,
  },

  // ── Small peaceful animals ─────────────────────────────────────────────
  rabbit: {
    id: 'rabbit',
    name: 'Rabbit',
    type: 'monster',  // uses monster system but isHostile:false = peaceful animal
    atlas: 'creatures',
    frames: {
      idle: 'rabbit_idle_f01',
      walk: ['rabbit_walk_down_f01', 'rabbit_walk_down_f02'],
      run:  ['rabbit_walk_down_f01', 'rabbit_walk_down_f02'],
      attack: 'rabbit_flee_f01',
      dead: 'rabbit_idle_f01',
      fainted: 'rabbit_idle_f01',
      frozen: 'rabbit_idle_f01',
      alert: 'rabbit_flee_f01',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 8,
    speed: 100,          // fast little hopper
    damage: 0,
    isHostile: false,
    sightRange: 3,
    canWander: true,
    wanderRadius: 3,
    displaySize: 24,     // tiny! about half the hero height
    fleeRange: 128,      // flees when player gets within 2 tiles
  },

  squirrel: {
    id: 'squirrel',
    name: 'Squirrel',
    type: 'monster',
    atlas: 'creatures',
    frames: {
      idle: 'rabbit_idle_f02',
      walk: ['rabbit_walk_down_f01', 'rabbit_walk_down_f02'],
      run:  ['rabbit_walk_down_f01', 'rabbit_walk_down_f02'],
      attack: 'rabbit_idle_f01',
      dead: 'rabbit_idle_f02',
      fainted: 'rabbit_idle_f02',
      frozen: 'rabbit_idle_f02',
      alert: 'rabbit_walk_down_f01',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 6,
    speed: 120,
    damage: 0,
    isHostile: false,
    sightRange: 3,
    canWander: true,
    wanderRadius: 2,
    displaySize: 22,
    fleeRange: 96,
  },

  frog: {
    id: 'frog',
    name: 'Frog',
    type: 'monster',
    atlas: 'creatures',
    frames: {
      idle: 'rabbit_idle_f01',
      walk: ['rabbit_walk_down_f01', 'rabbit_walk_down_f02'],
      run:  ['rabbit_walk_down_f01', 'rabbit_walk_down_f02'],
      attack: 'rabbit_idle_f02',
      dead: 'rabbit_idle_f01',
      fainted: 'rabbit_idle_f01',
      frozen: 'rabbit_idle_f01',
      alert: 'rabbit_idle_f02',
    },
    movementFlags: { ...DEFAULT_FLAGS, canSwim: true },
    hp: 10,
    speed: 80,
    damage: 0,
    isHostile: false,
    sightRange: 2,
    canWander: true,
    wanderRadius: 2,
    displaySize: 20,
    fleeRange: 80,
  },

  butterfly: {
    id: 'butterfly',
    name: 'Butterfly',
    type: 'monster',
    atlas: 'creatures',
    frames: {
      idle: 'bird_idle_f01',
      walk: ['bird_fly_f01', 'bird_fly_f02'],
      run:  ['bird_fly_f01', 'bird_fly_f02'],
      attack: 'bird_sing_f01',
      dead: 'bird_idle_f01',
      fainted: 'bird_idle_f01',
      frozen: 'bird_idle_f01',
      alert: 'bird_fly_f01',
    },
    movementFlags: { ...DEFAULT_FLAGS, canFly: true },
    hp: 4,
    speed: 70,
    damage: 0,
    isHostile: false,
    sightRange: 2,
    canWander: true,
    wanderRadius: 4,     // flutters around a wider area
    displaySize: 20,
    fleeRange: 64,
  },

  hedgehog: {
    id: 'hedgehog',
    name: 'Hedgehog',
    type: 'monster',
    atlas: 'creatures',
    frames: {
      idle: 'rabbit_idle_f02',
      walk: ['rabbit_walk_down_f01', 'rabbit_walk_down_f02'],
      run:  ['rabbit_flee_f02'],
      attack: 'rabbit_flee_f02',
      dead: 'rabbit_idle_f02',
      fainted: 'rabbit_idle_f02',
      frozen: 'rabbit_idle_f02',
      alert: 'rabbit_idle_f01',
    },
    movementFlags: DEFAULT_FLAGS,
    hp: 15,
    speed: 50,           // slow but sturdy
    damage: 0,
    isHostile: false,
    sightRange: 2,
    canWander: true,
    wanderRadius: 2,
    displaySize: 22,
    fleeRange: 48,       // barely flees — curls up instead
  },

  // ── Slime monster variants ─────────────────────────────────────────────
  slime_green: {
    id: 'slime_green',
    name: 'Green Slime',
    type: 'monster',
    atlas: 'creatures',
    frames: {
      idle: 'slime_idle_f01',
      walk: ['slime_move_left_f01', 'slime_move_right_f01'],
      run:  ['slime_move_left_f01', 'slime_move_right_f01'],
      attack: 'slime_angry_f01',
      dead: 'slime_idle_f01',
      fainted: 'slime_idle_f01',
      frozen: 'slime_idle_f01',
      alert: 'slime_angry_f01',
    },
    movementFlags: { ...DEFAULT_FLAGS, canSwim: true },
    hp: 20,
    speed: 45,
    damage: 1,
    isHostile: false,    // wanders peacefully unless provoked
    sightRange: 3,
    canWander: true,
    wanderRadius: 3,
    displaySize: 28,
  },

  slime_blue: {
    id: 'slime_blue',
    name: 'Blue Slime',
    type: 'monster',
    atlas: 'creatures',
    frames: {
      idle: 'slime_idle_f02',
      walk: ['slime_move_left_f01', 'slime_move_right_f01'],
      run:  ['slime_move_left_f01', 'slime_move_right_f01'],
      attack: 'slime_idle_f01',
      dead: 'slime_idle_f02',
      fainted: 'slime_idle_f01',
      frozen: 'slime_idle_f02',
      alert: 'slime_idle_f02',
    },
    movementFlags: { ...DEFAULT_FLAGS, canSwim: true },
    hp: 15,
    speed: 25,           // very slow, sleepy
    damage: 0,
    isHostile: false,
    sightRange: 2,
    canWander: true,
    wanderRadius: 2,
    displaySize: 28,
  },

  slime_red: {
    id: 'slime_red',
    name: 'Red Slime',
    type: 'monster',
    atlas: 'creatures',
    frames: {
      idle: 'slime_idle_f01',
      walk: ['slime_move_left_f01', 'slime_move_right_f01'],
      run:  ['slime_move_left_f01', 'slime_move_right_f01'],
      attack: 'slime_angry_f02',
      dead: 'slime_idle_f01',
      fainted: 'slime_idle_f01',
      frozen: 'slime_idle_f01',
      alert: 'slime_angry_f02',
    },
    movementFlags: { ...DEFAULT_FLAGS, canSwim: true },
    hp: 30,
    speed: 75,           // fast and aggressive
    damage: 2,
    isHostile: true,     // actively chases player!
    sightRange: 5,
    canWander: true,
    wanderRadius: 4,
    displaySize: 32,
  },

  slime_king: {
    id: 'slime_king',
    name: 'King Slime',
    type: 'boss',
    atlas: 'creatures',
    frames: {
      idle: 'slime_idle_f02',
      walk: ['slime_move_left_f01', 'slime_move_right_f01'],
      run:  ['slime_move_left_f01', 'slime_move_right_f01'],
      attack: 'slime_split_f01',
      dead: 'slime_idle_f02',
      fainted: 'slime_idle_f02',
      frozen: 'slime_idle_f02',
      alert: 'slime_split_f01',
    },
    movementFlags: { ...DEFAULT_FLAGS, canSwim: true },
    hp: 150,
    speed: 55,
    damage: 4,
    isHostile: true,
    sightRange: 7,
    canWander: true,
    wanderRadius: 5,
    displaySize: 48,     // large boss slime
  },
};
